version: 2
updates:
  # GitHub Actions
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    commit-message:
      prefix: "Dependabot: "
  # Python
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: daily
    commit-message:
      prefix: "Dependabot: "
